version: '3.7'

services:
  proxy:
    build: ./proxy
    container_name: proxy
    image: jwilder/nginx-proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      #- ./proxy/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro

  proxy-letsencrypt:
    container_name: letsencrypt
    depends_on:
      - "proxy"
    env_file: ./proxy-letsencrypt/.env
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  certs:
  html:
  vhost.d:

networks:
  default:
    external:
      name: nginx-proxy
