# This needs at least compose 1.6.0
version: '2'

services:
  mysqldata:
    image: mysql:5.7
    command: /bin/true

  mysql:
    image: mysql:5.7
    volumes_from:
      - mysqldata
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: huginn
      MYSQL_USER: huginn
      MYSQL_PASSWORD: myhuginnpassword

  huginn:
    image: huginn/huginn
    restart: always
    environment:
      VIRTUAL_HOST: huginn.cashweaver.com
      LETSENCRYPT_HOST: huginn.cashweaver.com
      VIRTUAL_PORT: 3000
      DOMAIN: huginn.cashweaver.com
      PORT: 3000
      HUGINN_DATABASE_NAME: huginn
      HUGINN_DATABASE_USERNAME: root
      HUGINN_DATABASE_PASSWORD: myrootpassword
      INTENTIONALLY_SLEEP: 10
      #DATABASE_INITIAL_CONNECT_MAX_RETRIES: 5
      MYSQL_PORT_3306_TCP_ADDR: mysql
      MYSQL_PORT_3306_TCP_PORT: 3306
    ports:
      - 3000:3000
    links:
      - mysql

networks:
  default:
    external:
      name: nginx-proxy
