version: '3.7'

services:
  monica:
    image: monicahq/monicahq:fpm
    #depends_on: 
      #- monica_cron
      #- monica_db
      #- monica_queue
    env_file: 
      - ./monica/.env
      - ./monica/.env-secrets
    #ports: 
      #- 3000:9000
    restart: always
    volumes: 
      - monica_vol_data:/var/www/monica/storage
      - monica_vol_www:/var/www/monica

  monica_cron:
    image: monicahq/monicahq:fpm
    depends_on: 
      - monica_db
    env_file: 
      - ./monica/.env
      - ./monica/.env-secrets
    command: cron.sh
    #ports: 
      #- 3000:9000
    restart: always
    volumes: 
      - monica_vol_data:/var/www/monica/storage
      - monica_vol_www:/var/www/monica:ro

  monica_queue:
    image: monicahq/monicahq:fpm
    depends_on: 
      - monica_db
    env_file: 
      - ./monica/.env
      - ./monica/.env-secrets
    command: queue.sh
    #ports: 
      #- 3000:9000
    restart: always
    volumes: 
      - monica_vol_data:/var/www/monica/storage
      - monica_vol_www:/var/www/monica:ro

  monica_db:
    env_file:
      - ./monica_db/.env
      - ./monica_db/.env-secrets
    image: mysql:5.7
    restart: always
    volumes: 
      - monica-vol-db:/var/lib/mysql

  monica_web:
    build: ./monica_web
    restart: always
    depends_on:
      - monica
    environment:
      - VIRTUAL_HOST=monica.cashweaver.com
      - LETSENCRYPT_HOST=monica.cashweaver.com
      - LETSENCRYPT_EMAIL=cashbweaver@gmail.com
    volumes:
      - monica_vol_data:/var/www/monica/storage:ro
      - monica_vol_www:/var/www/monica:ro

volumes:
  monica_vol_data: 
    name: monica_vol_data
  monica_vol_www: 
    name: monica_vol_www
  monica-vol-db:
    name: monica-vol-db

networks:
  default:
    external:
      name: nginx-proxy
