version: '3.7'

services:
  monica:
    depends_on:
      - db
    env_file: 
      - ./monica/.env 
      - ./monica/.env-secrets
    image: monicahq/monicahq:fpm
    restart: always
    volumes: 
      - vol-data:/var/www/monica/storage 
      - vol-www:/var/www/monica

  cron:
    command: cron.sh
    depends_on: 
      - db
    env_file: 
      - ./monica/.env
      - ./monica/.env-secrets
    image: monicahq/monicahq:fpm
    restart: always
    volumes: 
      - vol-data:/var/www/monica/storage
      - vol-www:/var/www/monica:ro

  queue:
    command: queue.sh
    depends_on: 
      - db
    env_file: 
      - ./monica/.env
      - ./monica/.env-secrets
    image: monicahq/monicahq:fpm
    restart: always
    volumes: 
      - vol-data:/var/www/monica/storage
      - vol-www:/var/www/monica:ro

  db:
    env_file:
      - ./db/.env
      - ./db/.env-secrets
    image: mysql:5.7
    restart: always
    volumes: 
      - vol-mysql:/var/lib/mysql

  web:
    build: ./web
    depends_on:
      - monica
    env_file:
      - ./web/.env
    restart: always
    volumes:
      - vol-data:/var/www/monica/storage:ro
      - vol-www:/var/www/monica:ro

volumes:
  vol-data: 
    name: vol-data
  vol-www: 
    name: vol-www
  vol-mysql:
    name: vol-mysql

networks:
  default:
    external:
      name: nginx-proxy
